queue_rules:
  - name: duplicated default from automatic merge backports from Mergify
    queue_conditions:
      - label!=work-in-progress
      - '#approved-reviews-by>=1'
      - check-success=test (docs-gnocchi-web)
      - check-success=test (build)
      - check-success=test (pep8)
      - check-success=test (py38)
      - check-success=test (py39)
      - check-success=test (py311)
      - base~=^stable/.*
      - label!=work-in-progress
      - author=mergify[bot]
    merge_conditions: []
    merge_method: merge
  - name: default
    queue_conditions:
      - label!=work-in-progress
      - '#approved-reviews-by>=1'
      - check-success=test (docs-gnocchi-web)
      - check-success=test (build)
      - check-success=test (pep8)
      - check-success=test (py38)
      - check-success=test (py39)
      - check-success=test (py311)
    merge_conditions:
      - check-success=test (docs-gnocchi-web)
      - check-success=test (build)
      - check-success=test (pep8)
      - check-success=test (py38)
      - check-success=test (py39)
      - check-success=test (py311)
    merge_method: merge

pull_request_rules:
  - name: dismiss reviews on additional commit
    actions:
      dismiss_reviews: {}
    conditions: []
  - name: automatic merge + automatic merge backports from Mergify
    conditions: []
    actions:
      queue:
