pull_request_rules:
  - name: automatic merge
    actions:
      merge:
        method: rebase
        rebase_fallback: merge
        strict: true
    conditions:
    - label!=work-in-progress
    - '#approved-reviews-by>=2'
    - status-success=continuous-integration/travis-ci/pr
  - name: merge backport to stable with one review
    actions:
      merge:
        method: rebase
        rebase_fallback: merge
        strict: true
    conditions:
    - base~=^stable/.*
    - label!=work-in-progress
    - '#approved-reviews-by>=1'
    - status-success=continuous-integration/travis-ci/pr
  - name: automatic merge backports from Mergify
    actions:
      merge:
        method: rebase
        rebase_fallback: merge
        strict: true
    conditions:
    - base~=^stable/.*
    - label!=work-in-progress
    - author=mergify[bot]
    - status-success=continuous-integration/travis-ci/pr
