language: python
sudo: required

services:
  - docker

cache:
  directories:
    - ~/.cache/pip
env:
  - TARGET: pep8
  - TARGET: py27
  - TARGET: py35
  - TARGET: docs-gnocchi.xyz

before_script:
  # Only run if this is a pull-request
  - if \[ "$TRAVIS_PULL_REQUEST" != "false" -o  -n "$TRAVIS_TAG" \]; then
      docker pull gnocchixyz/ci-tools:latest ;
    fi
script:
  # Only run if this is a pull-request
  - if \[ "$TRAVIS_PULL_REQUEST" != "false" -o  -n "$TRAVIS_TAG" \]; then
      docker run -v ~/.cache/pip:/home/tester/.cache/pip -v $(pwd):/home/tester/src gnocchixyz/ci-tools:latest tox -e ${TARGET} ;
    fi

notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org#gnocchi"

deploy:
  provider: pypi
  user: jd
  password:
    secure: eQzA9F55MW2v2eQysmV38tyuj0cqYaQh6iTWLf5ZBBqiSu8OwmJeouRCDpHOM93XDerLwzlNfmq2NwaP3lxbhc1kU9fxkyI9CbX4fQzHkrl30Eee9fq82qfnH+cBt9zZBGgk+HEClHxZINiQKF1NTzWA7PDkGRnLDfBrMqUum1FqYoli1XNoCOwgYRcI0UdaE96qqSqE4rlp4vuAR8sfDSh6SxLBUtEHzZM2ScreRZV11DwRSB5a9nc+PGAU6FdmSU6uil2kojmKU84q/+BbSpRG4Ch10MDWIN3UIuPfP4t8zhgC3grfTzq7Q+9l6VYFeQHdAsoHb050d9YabnZNxUqDt/ZIABKcpu/YiZzIXGbpGh4fw4mVupbOoFpVFg1Zg/nQAv99HYDtp5QwqYbA5T3LZXDi2v6+oPWCrBh5ll9bk7DhWsPhBFj5jjBIDY4sgXuRTLaGbik+CLxnmqR/KwOFtLM9cJQjCdfpi1K9VIqNI+NpIgQN5++FhqkL2vWTeiypraK5p1MiuHN0+UA2bdnKpadzE6VuIqjIbfZIKHRZDMkejQ9ruZgIMUTscafyMf9mY9NHXtqD6PA1rK/S4+3n5KIFRDFVVsBUPpao4jIFzaLfSPYciC4PrhyVNzfoIRnlStzuiUPjU0S89UwRAQiapf0NMNmXK2CMWvR9xIg=
  on:
    all_branches: true
    tags: true
  distributions: "sdist bdist_wheel"
